import streamlit as str

# Set page layout to wide and corporate dark theme look
str.set_page_config(
    page_title="AgentBRD - Autonomous Corporate Analyst",
    page_icon="💼",
    layout="wide"
)

# Custom Styling for Enterprise Look
str.markdown("""
    <style>
    .main-title { font-size: 38px; color: #38bdf8; font-weight: bold; margin-bottom: 5px; }
    .sub-title { font-size: 18px; color: #94a3b8; margin-bottom: 25px; }
    .feature-box { background-color: #0f172a; padding: 20px; border-radius: 10px; border-left: 5px solid #38bdf8; margin-bottom: 15px; }
    </style>
""", unsafe_allow_html=True)

# Sidebar Configuration
with str.sidebar:
    str.image("https://img.icons8.com/external-flatart-icons-flat-flatarticons/128/external-agent-customer-support-flatart-icons-flat-flatarticons.png", width=80)
    str.markdown("## **AgentBRD Dashboard**")
    str.info("⚡ Powered by Gemini 1.5 Pro & Google Cloud")
    
    str.markdown("---")
    str.markdown("### **Project Metadata**")
    str.markdown("- **Team:** AI Agentic")
    str.markdown("- **Track:** Google Cloud / Google AI Studio")
    str.markdown("- **Version:** v1.0.0")

# Main Screen Header
str.markdown('<div class="main-title">💼 AgentBRD</div>', unsafe_allow_html=True)
str.markdown('<div class="sub-title">Autonomous Multi-Modal AI Agent transforming raw business assets into standard corporate BRDs in minutes.</div>', unsafe_allow_html=True)

# Layout: Split into two columns (Left: Ingestion, Right: Output Display)
col1, col2 = str.columns([1, 1.2])

with col1:
    str.markdown("### 📥 Multi-Modal Asset Ingestion")
    str.write("Upload client transcripts, raw notes, whiteboard wireframes, or audio files.")
    
    # Text notes input
    raw_notes = str.text_area("✍️ Raw Meeting Notes / Slack Transcripts", placeholder="Paste unorganized corporate chats, notes or requirement snippets here...")
    
    # File Uploader for Multi-Modal Data
    uploaded_files = str.file_uploader(
        "📁 Upload Documents & Visuals (PDF, DOCX, PNG, JPEG, MP3)", 
        accept_multiple_files=True
    )
    
    # Submit Button to trigger AI Agent
    generate_btn = str.button("🚀 Run AgentBRD Analysis", use_container_width=True)

with col2:
    str.markdown("### 📄 Generated Business Requirements Document (BRD)")
    
    if generate_btn:
        if not raw_notes and not uploaded_files:
            str.warning("⚠️ Please provide some input assets (notes or files) for the agent to analyze.")
        else:
            with str.spinner("🤖 AgentBRD Sub-agents are analyzing sources, verifying structural guardrails, and mapping explainability links..."):
                # Simulating execution layout for Round 2 presentation
                str.success("✅ BRD successfully compiled with 100% data lineage anchoring!")
                
                # Mock Corporate BRD output based on user's project details
                with str.expander("🔍 View Section 1: Executive Summary & Context", expanded=True):
                    str.markdown("#### **1.1 Project Objective**")
                    str.write("Automate the manual BA bottleneck by cutting document creation cycles down to under 15 minutes.")
                    str.markdown("#### **1.2 Source Lineage (Explainability Anchor)**")
                    str.info("🔗 Derived from: User Ingested Raw Assets (Confidence Score: 98.7%)")
                
                with str.expander("🔍 View Section 2: Technical Architecture Requirements"):
                    str.markdown("#### **2.1 Google Cloud Infrastructure**")
                    str.write("- **Google Cloud Storage:** Landing zone for raw multi-modal business metadata.")
                    str.write("- **BigQuery:** Core metrics telemetry and logs engine.")
                    str.write("- **Gemini 1.5 Pro:** High-context 2M token analysis execution layer.")
                
                # Download Button for Corporate Export
                str.download_button(
                    label="📥 Export Corporate BRD (.md format)",
                    data="# Business Requirements Document (BRD)\n\nGenerated by AgentBRD successfully.",
                    file_name="AgentBRD_Generated_Document.md",
                    mime="text/markdown",
                    use_container_width=True
                )
    else:
        str.info("ℹ️ System Idle. Ingest raw client data on the left panel and click 'Run' to activate the autonomous multi-agent pipeline.")

# Footer Area
str.markdown("---")
str.markdown("<p style='text-align: center; color: #64748b;'>Developed & Conceptualized by Team AI Agentic · Aprajita Singh & Divyanshu Singh</p>", unsafe_allow_html=True)
